### ISSUE TITLE
question about adobe json converter

### ISSUE THREAD

**Issue by Vortex2Oblivion** [swordcube/NovaEngine-Godot-FNF#12]
### What is your question?

does it only work with jsons made in 2018 or something?
i get an error when i try to use it.
ik its in beta so its gonna have issues but i figured i should ask anyways

**Comment by lavycat** [comment]
not sure can you show the json??

**Comment by swordcube** [comment]
the converter has only been tested with flash cs6, can you send the json here? Btw it only converts sparrow atlas jsons

not the other kind of atlas json

**Comment by Vortex2Oblivion** [comment]
ah my bad
i was testing converting a texture atlas json
