### ISSUE TITLE
Game crashes after going into options

### ISSUE THREAD

**Issue by RUvlad1** [swordcube/NovaEngine-Godot-FNF#13]
### Cause of the bug

Exactly what the title says, I just got the game too and I never used any older versions

https://github.com/swordcube/NovaEngine-Godot-FNF/assets/60317461/80567629-3405-413e-bb3a-97dca416d54d

### Your Platform

Windows

**Comment by RUvlad1** [comment]
[godot.log](https://github.com/swordcube/NovaEngine-Godot-FNF/files/11747543/godot.log)
I found a log file in the AppData folder, hope this helps

**Comment by RUvlad1** [comment]
The issue doesn't seem to happen after importing the project in Godot and running the game from there, the issue occurs when I get the game from the Releases page

**Comment by swordcube** [comment]
I think I know exactly what happened

I will make a patch release soon

**Comment by swordcube** [comment]
Can you test this build for me and report if the crash still occurs?
(Had to upload to mediafire, github wouldn't let me upload it here)

https://www.mediafire.com/file/j5i9ejx939dl4ac/Nova_Godot_Test_Build_-_Windows.zip/file

**Comment by RUvlad1** [comment]
> Can you test this build for me and report if the crash still occurs? (Had to upload to mediafire, github wouldn't let me upload it here)
> 
> https://www.mediafire.com/file/j5i9ejx939dl4ac/Nova_Godot_Test_Build_-_Windows.zip/file

it works

**Comment by swordcube** [comment]
the new release is out
https://github.com/swordcube/NovaEngine-Godot-FNF/
