### ISSUE TITLE
Possible Suggestion for making the XML Converter a Plugin for other games to use???

### ISSUE THREAD

**Issue by rayanmargham** [swordcube/NovaEngine-Godot-FNF#4]
I wanna use this for my OWN fnf godot project (not really, I'm just prototyping the arrow system for me to then do in rust with bevy). How would I do that?

**Comment by Leather128** [comment]
you see sir, you use the code and scene file in your project, and then you're done. maybe you'll have to fix a dependency or two because of file paths but still it should just work iirc?

**Comment by rayanmargham** [comment]
thanks bro
