### ISSUE TITLE
how make notes 3d uwu

### ISSUE THREAD

**Issue by rayanmargham** [swordcube/NovaEngine-Godot-FNF#5]
how to turn this
`Note.y = (strumLine.y - (Conductor.songPosition - daNote.strumTime) * (0.45 * FlxMath.roundDecimal(SONG.speed, 2)));`

into something for a sprite3d, or better yet tell me how it works because its 3:40 am and godot hates me.
I know i need to convert it to 3d space somehow and i tried that project method for the camera3d and ow my brain hurts

my excuse for this being related to nova engine: im doing this in nova engine trust definitely am 100% so true im so believable

**Comment by rayanmargham** [comment]
figured it out with unproject
note.position.y = $Camera3D.project_position(Vector2(0, $Camera3D.unproject_position(strumLine.position).y - ((conduct.songpos - note.strumTime)) * (0.45 * round_to_dec(conduct.loadedsong.speed, 2))), 5).y

**Comment by swordcube** [comment]
okay then?
