### ISSUE TITLE
GF and note position

### ISSUE THREAD

**Issue by ACoolioDude** [swordcube/NovaEngine-Godot-FNF#9]
### Cause of the bug

It's that need to look like this?
![Snimak ekrana (5)](https://user-images.githubusercontent.com/126715034/233869994-7985d187-7205-4dff-b356-c8aff63a7cb4.png)

### Your Platform

Windows

**Comment by swordcube** [comment]
you messed with something, atleast i think you did because
this should never happen on default nova

![image](https://user-images.githubusercontent.com/49110074/234115843-0ee390ab-b908-4fba-967d-882f01fd067b.png)

**Comment by swordcube** [comment]
here's an image without centered notefield enabled
![image](https://user-images.githubusercontent.com/49110074/234116114-b632130d-06f2-459d-9f99-0c16efef5e0a.png)
